### ISSUE TITLE
how does install one with npm?

### ISSUE THREAD

**Issue by Mactub07** [clauderic/react-native-infinite-calendar#2]

**Comment by joshjhargreaves** [comment]
As you would any package not published to npm: 'npm install githubname/reponame'

**Comment by clauderic** [comment]
This hasn't been released to npm yet, but as @joshyhargreaves pointed out, you can install it by running

```
npm install clauderic/react-native-infinite-calendar
```

**Comment by lucasbento** [comment]
@clauderic: just wondering, why haven't you released it to npm yet?
