### ISSUE TITLE
change location of Flatlist

### ISSUE THREAD

**Issue by Mactub07** [clauderic/react-native-infinite-calendar#3]
for current "react-native": "^0.42.3",
FlatList must be imported from "react-native"

ex. import {FlatList} from 'react-native';
https://facebook.github.io/react-native/docs/flatlist.html

**Comment by clauderic** [comment]
Good point, thanks! https://github.com/clauderic/react-native-infinite-calendar/commit/c1e39ab36dab4be7161e36703c37b4c272442e15
